apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: biometric-shards

resources:
- ../../base
- nodepool.yaml
- aksnodeclass.yaml

patchesStrategicMerge:
- statefulset-patch.yaml

namePrefix: explore-

labels:
- pairs:
    deployment-phase: exploration
  includeSelectors: false
  includeTemplates: true
