apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: biometric-shards

resources:
- namespace.yaml
- priorityclass.yaml
- service-headless.yaml
- service-loadbalancer.yaml
- statefulset.yaml
- poddisruptionbudget.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: biometric-shards

# Allow customization via patches in overlays
configurations:
- kustomizeconfig.yaml
