apiVersion: v1
kind: Service
metadata:
  name: biometric-lb
  namespace: biometric-shards
  labels:
    app.kubernetes.io/name: biometric-shards
    app.kubernetes.io/component: loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: biometric-shard
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
